### ISSUE TITLE
[Adding] Filtering Guide: Debanding section - binarize/saturate retinex mask

### ISSUE THREAD

**Issue by Z4ST1N** [eXmendiC/vapoursynth_guide#1]
Since the retinex edgemask part in the guide doesn't say anything about it, here it is:
(note: zz.range(clip, number) is gradfun3's mask with thr det=2 and mask=number)
```
input = input
yl_8 = kgf.getY(input)
yl = yl_8.fmtc.bitdepth(bits=16)

grayclip = input.std.BlankClip(1920*3, 1080*3, format=vs.YUV420P8, color=[128,128,128])
chrmclip = core.std.StackHorizontal([input,input,input])
uvclip = core.std.StackVertical([grayclip,chrmclip])

yl_smd = haf.SMDegrain(yl, tr=2, thSAD=100, RefineMotion=True, prefilter=3) #tr=4, thSAD=200 for Rakudai
yl_smd_8round = yl_smd.fmtc.bitdepth(bits=8, dmode=1)
yl_smd_8errdf = yl_smd.fmtc.bitdepth(bits=8, dmode=3)

mm1=zz.range(yl_smd_8round,1).std.Binarize(2).rgvs.RemoveGrain(22)
mm2=zz.range(yl_smd_8round,2).std.Binarize(2).rgvs.RemoveGrain(22).rgvs.RemoveGrain(11)
mm3=zz.range(yl_smd_8round,3).std.Binarize(2).rgvs.RemoveGrain(22).rgvs.RemoveGrain(11).rgvs.RemoveGrain(20)

ret=kgf.retinex_edgemask(yl_smd)
retb=ret.std.Binarize(3000)
rets=ret.std.Expr("x 2000 > x 10 * x ?")
ret=core.std.StackVertical([retb,rets])

ret1=ret.std.Inflate()
ret2=ret.std.Maximum().std.Inflate()
ret3=ret.std.Maximum().std.Maximum().std.Inflate().std.Inflate()

top=core.std.StackHorizontal([mm1,mm2,mm3])

mid=core.std.StackHorizontal([ret1,ret2,ret3])
mid=mid.fmtc.bitdepth(bits=8, dmode=1, fulls=True, fulld=True)

btm=core.std.StackHorizontal([yl_8, yl_smd_8round, yl_smd_8errdf])

preview = core.std.StackVertical([top,mid,btm])
zz.mergechroma(preview,uvclip).set_output()
```

example images:
Oregairu Zoku (good quality, little banding)
https://my.mixtape.moe/mxfigi.png
https://my.mixtape.moe/rqxaqe.png
https://my.mixtape.moe/cehrrf.png

Rakudai Kishi no Cavalry (is this even 8 bits?)
https://my.mixtape.moe/mzanne.png
https://my.mixtape.moe/qcxtoo.png
https://my.mixtape.moe/fovqct.png
https://my.mixtape.moe/qtuihr.png

top row (gradfun3) --- mask=1 | mask=2 | mask=3
2nd row(retinex - binarize) --- thin | normal | thick
3nd row(retinex - saturate) --- thin | normal | thick
bottom row (source) --- BDMV | denoised (no dither) | denoised (error diffusion)

**Comment by eXmendiC** [comment]
Added: https://iamscum.wordpress.com/encoding-stuff/filtering-with-vapoursynth/debanding/
