### ISSUE TITLE
[V-Mistake] Denosing/Degraining section

### ISSUE THREAD

**Issue by Z4ST1N** [eXmendiC/vapoursynth_guide#2]
At the very bottom of the denoiser section, the last sentence says "It works as well for hybriddenoise." but hybriddenoise doesnt have a ref parameter. From kagefunc.py:

> def hybriddenoise(src, knl=0.5, sigma=2, radius1=1):

You could probably just ask him to add it, tho. And if he does, you might wanna specify that you would (probably) only need to supply a GRAY clip for the ref, since hybriddenoise uses luma-only BM3D. As in, tell them to do this:
```
srcY = kgf.getY(src)
ref = srcY.dfttest.DFTTest(sigma=3,tbsize=1)
out = kgf.hybriddenoise(src, knl=0.5, sigma=1, radius1=1, ref=ref) 
```

**Comment by eXmendiC** [comment]
Kageru said he won't support "ref" clips.
I fixed it with "It doesn't work for hybriddenoise"
